* boris REPL in emacs

This is an emacs major mode running the [[https://github.com/d11wtq/boris][boris php REPL]] by [[https://github.com/d11wtq][Chris
'Chippie' Corbyn]] in an emacs buffer.

* Heritage

As of now this mode does not contain any real effort by me, other
than renaming the symbols; all the code is by [[https://github.com/abicky][Takeshi Arabiki]], who's
[[https://github.com/abicky/nodejs-repl.el][nodejs-repl]] I took to run boris instead of node, making only the
slight changes needed to get boris running and the buffer working.

* Installation
** Prerequisites
Not surprisingly you have to have =boris= installed.
** Install

*** via github
Clone the =php-boris= repository in a fitting location (I use
=.emacs.d/src= for repositories):

#+BEGIN_SRC sh
  cd ~/.emacs.d/src
  git clone git://github.com/tomterl/php-boris.git
#+END_SRC
*** via =list-packages=

=php-boris= is available via [[http://melpa.milkbox.net/][MELPA]].

** Setup
Add the following to your emacs setup

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path (expand-file-name "~/.emacs.d/src/php-boris"))
  (require 'php-boris)
#+END_SRC
** Configure
If =boris= is not in your =$PATH=, set the location with

#+BEGIN_SRC emacs-lisp
  (setq 'php-boris-command "/path/to/boris")
#+END_SRC

* Usage

Start boris with =M-x php-boris=. For keybindings see =commint-mode=.

* Bugs

- =boris= has no TAB-completion, repeated TAB presses may freeze your
  emacs, use =C-g= to break the loop.
- continuation prompts are not yet correctly set, so that commint
  keybindings will not work, stating "not a command line" in the
  minibuffer

Other than that, this makes boris perfectly usable inside emacs, a
nice help to php developers.
